version: '2'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 957957957
      MYSQL_DATABASE: blog2
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 957957957
    ports:
      - "3307:3306"
  app:
    build: .
    command: bundle exec rails s
    volumes:
      - ".:/Blog2"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: blog2
      DB_PASSWORD:
      DB_HOST: db