version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/Blog2"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
